version: '3.9'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: tgadsbackend
    ports:
      - '3000:3000'
    depends_on:
      - redis
    restart: unless-stopped
    networks:
      - apinet
      - gateway
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_PASSWORD: 1234

  redis:
    image: redis
    restart: always
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - rdsdata:/root/redis
      - cache:/data
    environment:
      - REDIS_PASSWORD=1234
      - REDIS_DATABASES=16
    networks:
      - apinet


volumes:
  cache:
  chdata:
  pgdata:
  rdsdata:

networks:
  apinet:
    name: apinet
    driver: bridge
    ipam:
      config:
        - subnet: "192.168.32.0/24"
  gateway:
    name: gateway
    driver: bridge
